// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CronManager is an autogenerated mock type for the CronManager type
type CronManager struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *CronManager) Start() {
	_m.Called()
}

// NewCronManager creates a new instance of CronManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCronManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *CronManager {
	mock := &CronManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
