// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	models "github.com/kkcaz/shu-dades-server/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ProductUseCase is an autogenerated mock type for the ProductUseCase type
type ProductUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: product
func (_m *ProductUseCase) Create(product models.Product) error {
	ret := _m.Called(product)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *ProductUseCase) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *ProductUseCase) Get(id string) (*models.Product, error) {
	ret := _m.Called(id)

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *ProductUseCase) GetAll() ([]models.Product, error) {
	ret := _m.Called()

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Product, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductSubscriptions provides a mock function with given fields: userId
func (_m *ProductUseCase) GetProductSubscriptions(userId string) ([]models.ProductSubscription, error) {
	ret := _m.Called(userId)

	var r0 []models.ProductSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.ProductSubscription, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) []models.ProductSubscription); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ProductSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: pageNumber, pageSize, sortBy, order
func (_m *ProductUseCase) Search(pageNumber int, pageSize int, sortBy models.SortBy, order models.Order) ([]models.Product, error) {
	ret := _m.Called(pageNumber, pageSize, sortBy, order)

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, models.SortBy, models.Order) ([]models.Product, error)); ok {
		return rf(pageNumber, pageSize, sortBy, order)
	}
	if rf, ok := ret.Get(0).(func(int, int, models.SortBy, models.Order) []models.Product); ok {
		r0 = rf(pageNumber, pageSize, sortBy, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, models.SortBy, models.Order) error); ok {
		r1 = rf(pageNumber, pageSize, sortBy, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendProductNotifications provides a mock function with given fields: subType
func (_m *ProductUseCase) SendProductNotifications(subType string) error {
	ret := _m.Called(subType)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(subType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: productId, subType, userId
func (_m *ProductUseCase) Subscribe(productId string, subType string, userId string) error {
	ret := _m.Called(productId, subType, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(productId, subType, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: productId, subType, userId
func (_m *ProductUseCase) Unsubscribe(productId string, subType string, userId string) error {
	ret := _m.Called(productId, subType, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(productId, subType, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: product
func (_m *ProductUseCase) Update(product *models.Product) error {
	ret := _m.Called(product)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductUseCase creates a new instance of ProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductUseCase {
	mock := &ProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
